"""empty message

Revision ID: 758dd41a329d
Revises: 0482a4678a12
Create Date: 2021-07-05 20:25:38.332680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758dd41a329d'
down_revision = '0482a4678a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('front_photo', sa.Text(), nullable=True))
    op.drop_column('players', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('players', 'front_photo')
    # ### end Alembic commands ###
