"""empty message

Revision ID: a0a82542899c
Revises: 758dd41a329d
Create Date: 2021-07-08 16:20:37.120942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a82542899c'
down_revision = '758dd41a329d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    op.add_column('players', sa.Column('assists', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('games', sa.Text(), nullable=True))
    op.add_column('players', sa.Column('goals', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'goals')
    op.drop_column('players', 'games')
    op.drop_column('players', 'assists')
    op.create_table('stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('games', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('goals', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assist', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('xG', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name='stats_player_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stats_pkey')
    )
    # ### end Alembic commands ###
